# Generated by Django 3.2.9 on 2022-01-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item',
            new_name='name',
        ),
    ]
