# Generated by Django 3.2.9 on 2022-01-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_item_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='buyer_name',
            new_name='customer_name',
        ),
    ]
