# Generated by Django 4.1.dev20211206065911 on 2021-12-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=254)),
                ('buyer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_value', models.IntegerField(default=0)),
                ('disc_title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=254)),
                ('time_of_purchase', models.DateTimeField(verbose_name='date of purchase')),
                ('items', models.CharField(max_length=50)),
                ('amount_of_items', models.IntegerField(default=1)),
                ('disc_title', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
