# Generated by Django 4.1.dev20211206065911 on 2021-12-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customers_discounts_sells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='items',
        ),
    ]
