# Generated by Django 4.1.dev20211206065911 on 2021-12-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_sells_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.products'),
        ),
    ]
