# Generated by Django 4.1.dev20211206065911 on 2021-12-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_sell_delete_sells'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
