# Generated by Django 4.1.dev20211206065911 on 2021-12-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_discounts_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sell',
            old_name='items',
            new_name='product',
        ),
    ]
