# Generated by Django 4.1.dev20211206065911 on 2021-12-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_e_mail_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='items',
            new_name='item',
        ),
    ]
