# Generated by Django 4.1.dev20211206065911 on 2021-12-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_items_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='type',
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.product'),
        ),
    ]
